// This file is auto-generated. Do not edit manually.
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

#include "detail/legacy/broadway_copyist_legacy_map.h"
#include "detail/legacy/broadway_copyist_perc_legacy_map.h"
#include "detail/legacy/broadway_copyist_text_legacy_map.h"
#include "detail/legacy/broadway_copyist_text_ext_legacy_map.h"
#include "detail/legacy/chaconne_legacy_map.h"
#include "detail/legacy/engraver_font_extras_legacy_map.h"
#include "detail/legacy/engraver_font_set_legacy_map.h"
#include "detail/legacy/engraver_text_h_legacy_map.h"
#include "detail/legacy/engraver_text_ncs_legacy_map.h"
#include "detail/legacy/engraver_text_t_legacy_map.h"
#include "detail/legacy/engraver_time_legacy_map.h"
#include "detail/legacy/finale_alphanotes_legacy_map.h"
#include "detail/legacy/finale_copyist_text_legacy_map.h"
#include "detail/legacy/finale_copyist_text_ext_legacy_map.h"
#include "detail/legacy/finale_mallets_legacy_map.h"
#include "detail/legacy/finale_numerics_legacy_map.h"
#include "detail/legacy/finale_percussion_legacy_map.h"
#include "detail/legacy/gracenotes_legacy_map.h"
#include "detail/legacy/jazz_legacy_map.h"
#include "detail/legacy/jazzcord_legacy_map.h"
#include "detail/legacy/jazzperc_legacy_map.h"
#include "detail/legacy/jazztext_legacy_map.h"
#include "detail/legacy/jazztext_extended_legacy_map.h"
#include "detail/legacy/kousaku_legacy_map.h"
#include "detail/legacy/kousaku_percussion_legacy_map.h"
#include "detail/legacy/maestro_legacy_map.h"
#include "detail/legacy/maestro_percussion_legacy_map.h"
#include "detail/legacy/maestro_wide_legacy_map.h"
#include "detail/legacy/maestrotimes_legacy_map.h"
#include "detail/legacy/petrucci_legacy_map.h"
#include "detail/legacy/rentaro_legacy_map.h"
#include "detail/legacy/tamburo_legacy_map.h"

namespace smufl_mapping::detail {

struct LegacyFontMapping {
    std::string_view fontName;
    const std::pair<char32_t, LegacyGlyphInfo>* entries;
    std::size_t count;
};

constexpr LegacyFontMapping legacyFontMappings[] = {
    { "Broadway Copyist", legacy::broadwayCopyistLegacyGlyphs, std::size(legacy::broadwayCopyistLegacyGlyphs) },
    { "Broadway Copyist Perc", legacy::broadwayCopyistPercLegacyGlyphs, std::size(legacy::broadwayCopyistPercLegacyGlyphs) },
    { "Broadway Copyist Text", legacy::broadwayCopyistTextLegacyGlyphs, std::size(legacy::broadwayCopyistTextLegacyGlyphs) },
    { "Broadway Copyist Text Ext", legacy::broadwayCopyistTextExtLegacyGlyphs, std::size(legacy::broadwayCopyistTextExtLegacyGlyphs) },
    { "Chaconne", legacy::chaconneLegacyGlyphs, std::size(legacy::chaconneLegacyGlyphs) },
    { "Engraver Font Extras", legacy::engraverFontExtrasLegacyGlyphs, std::size(legacy::engraverFontExtrasLegacyGlyphs) },
    { "Engraver Font Set", legacy::engraverFontSetLegacyGlyphs, std::size(legacy::engraverFontSetLegacyGlyphs) },
    { "Engraver Text H", legacy::engraverTextHLegacyGlyphs, std::size(legacy::engraverTextHLegacyGlyphs) },
    { "Engraver Text NCS", legacy::engraverTextNcsLegacyGlyphs, std::size(legacy::engraverTextNcsLegacyGlyphs) },
    { "Engraver Text T", legacy::engraverTextTLegacyGlyphs, std::size(legacy::engraverTextTLegacyGlyphs) },
    { "Engraver Time", legacy::engraverTimeLegacyGlyphs, std::size(legacy::engraverTimeLegacyGlyphs) },
    { "Finale AlphaNotes", legacy::finaleAlphanotesLegacyGlyphs, std::size(legacy::finaleAlphanotesLegacyGlyphs) },
    { "Finale Copyist Text", legacy::finaleCopyistTextLegacyGlyphs, std::size(legacy::finaleCopyistTextLegacyGlyphs) },
    { "Finale Copyist Text Ext", legacy::finaleCopyistTextExtLegacyGlyphs, std::size(legacy::finaleCopyistTextExtLegacyGlyphs) },
    { "Finale Mallets", legacy::finaleMalletsLegacyGlyphs, std::size(legacy::finaleMalletsLegacyGlyphs) },
    { "Finale Numerics", legacy::finaleNumericsLegacyGlyphs, std::size(legacy::finaleNumericsLegacyGlyphs) },
    { "Finale Percussion", legacy::finalePercussionLegacyGlyphs, std::size(legacy::finalePercussionLegacyGlyphs) },
    { "GraceNotes", legacy::gracenotesLegacyGlyphs, std::size(legacy::gracenotesLegacyGlyphs) },
    { "Jazz", legacy::jazzLegacyGlyphs, std::size(legacy::jazzLegacyGlyphs) },
    { "JazzCord", legacy::jazzcordLegacyGlyphs, std::size(legacy::jazzcordLegacyGlyphs) },
    { "JazzPerc", legacy::jazzpercLegacyGlyphs, std::size(legacy::jazzpercLegacyGlyphs) },
    { "JazzText", legacy::jazztextLegacyGlyphs, std::size(legacy::jazztextLegacyGlyphs) },
    { "JazzText Extended", legacy::jazztextExtendedLegacyGlyphs, std::size(legacy::jazztextExtendedLegacyGlyphs) },
    { "Kousaku", legacy::kousakuLegacyGlyphs, std::size(legacy::kousakuLegacyGlyphs) },
    { "Kousaku Percussion", legacy::kousakuPercussionLegacyGlyphs, std::size(legacy::kousakuPercussionLegacyGlyphs) },
    { "Maestro", legacy::maestroLegacyGlyphs, std::size(legacy::maestroLegacyGlyphs) },
    { "Maestro Percussion", legacy::maestroPercussionLegacyGlyphs, std::size(legacy::maestroPercussionLegacyGlyphs) },
    { "Maestro Wide", legacy::maestroWideLegacyGlyphs, std::size(legacy::maestroWideLegacyGlyphs) },
    { "MaestroTimes", legacy::maestrotimesLegacyGlyphs, std::size(legacy::maestrotimesLegacyGlyphs) },
    { "Petrucci", legacy::petrucciLegacyGlyphs, std::size(legacy::petrucciLegacyGlyphs) },
    { "Rentaro", legacy::rentaroLegacyGlyphs, std::size(legacy::rentaroLegacyGlyphs) },
    { "Tamburo", legacy::tamburoLegacyGlyphs, std::size(legacy::tamburoLegacyGlyphs) },
};

} // namespace smufl_mapping::detail
