// This file is generated from Broadway Copyist Text.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> broadwayCopyistTextLegacyGlyphs[] = {
    {  91, { "enclosureParenOverLeft", 0xF723, "", SmuflGlyphSource::Smufl } },
    {  92, { "enclosureParenOverExtension", 0xF724, "", SmuflGlyphSource::Smufl } },
    {  93, { "enclosureParenOverRight", 0xF725, "", SmuflGlyphSource::Smufl } },
    {  94, { "enclosureParenOverExtensionLong", 0xF726, "", SmuflGlyphSource::Smufl } },
    {  95, { "enclosureBracketExtensionShort", 0xF727, "", SmuflGlyphSource::Smufl } },
    {  96, { "csymDiminished", 0xB0, "", SmuflGlyphSource::Smufl } },
    { 123, { "enclosureBracketLeft", 0xF720, "", SmuflGlyphSource::Smufl } },
    { 125, { "enclosureBracketRight", 0xF722, "", SmuflGlyphSource::Smufl } },
    { 126, { "enclosureClosed", 0xF74A, "", SmuflGlyphSource::Smufl } },
    { 128, { "enclosureBracketLeftLong", 0xF729, "", SmuflGlyphSource::Smufl } },
    { 129, { "enclosureBracketLongExtension", 0xF72A, "", SmuflGlyphSource::Smufl } },
    { 130, { "enclosureBracketRightLong", 0xF72B, "", SmuflGlyphSource::Smufl } },
    { 132, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl } },
    { 133, { "enclosureParenOverLeft2", 0xF72C, "", SmuflGlyphSource::Smufl } },
    { 134, { "enclosureParenOverExtensionLongAlt", 0xF72D, "", SmuflGlyphSource::Smufl } },
    { 135, { "enclosureParenOverRight2", 0xF72E, "", SmuflGlyphSource::Smufl } },
    { 136, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl } },
    { 137, { "metNote8thUp", 0xECA7, "", SmuflGlyphSource::Smufl } },
    { 138, { "metNote16thUp", 0xECA9, "", SmuflGlyphSource::Smufl } },
    { 140, { "metNoteQuarterUp", 0xECA5, "", SmuflGlyphSource::Smufl } },
    { 141, { "metNoteHalfUp", 0xECA3, "", SmuflGlyphSource::Smufl } },
    { 142, { "metNoteWhole", 0xECA2, "", SmuflGlyphSource::Smufl } },
    { 143, { "enclosureBracketExtension", 0xF721, "", SmuflGlyphSource::Smufl } },
    { 144, { "dynamicMezzo", 0xE521, "", SmuflGlyphSource::Smufl } },
    { 153, { "trademark", 0x2122, "", SmuflGlyphSource::Smufl } },
    { 157, { "enclosureParenUnderlineLeftAlt", 0xF735, "", SmuflGlyphSource::Smufl } },
    { 158, { "enclosureParenUnderlineExtension", 0xF736, "", SmuflGlyphSource::Smufl } },
    { 159, { "enclosureParenUnderlineRightShort", 0xF737, "", SmuflGlyphSource::Smufl } },
    { 160, { "enclosureParenUnderlineLeftLongAlt", 0xF738, "", SmuflGlyphSource::Smufl } },
    { 161, { "enclosureParenUnderlineExtensionLong", 0xF739, "", SmuflGlyphSource::Smufl } },
    { 162, { "enclosureParenUnderlineRightShortLong", 0xF73A, "", SmuflGlyphSource::Smufl } },
    { 175, { "enclosureParenOverLeft2Alt", 0xF741, "", SmuflGlyphSource::Smufl } },
    { 176, { "enclosureParenOverExtension2", 0xF742, "", SmuflGlyphSource::Smufl } },
    { 177, { "enclosureParenOverRight2Alt", 0xF743, "", SmuflGlyphSource::Smufl } },
    { 178, { "enclosureParenOverLeft2Long", 0xF744, "", SmuflGlyphSource::Smufl } },
    { 179, { "enclosureParenOverExtension2Long", 0xF745, "", SmuflGlyphSource::Smufl } },
    { 180, { "enclosureParenOverRight2Long", 0xF746, "", SmuflGlyphSource::Smufl } },
    { 181, { "enclosureParenUnderlineLeftAlt2", 0xF747, "", SmuflGlyphSource::Smufl } },
    { 182, { "enclosureParenUnderlineExtensionAlt", 0xF748, "", SmuflGlyphSource::Smufl } },
    { 183, { "enclosureParenUnderlineRightShortAlt2", 0xF749, "", SmuflGlyphSource::Smufl } },
    { 184, { "enclosureParenUnderlineRight", 0xF731, "", SmuflGlyphSource::Smufl } },
    { 191, { "zero", 0x30, "", SmuflGlyphSource::Smufl } },
    { 192, { "one", 0x31, "", SmuflGlyphSource::Smufl } },
    { 193, { "two", 0x32, "", SmuflGlyphSource::Smufl } },
    { 194, { "three", 0x33, "", SmuflGlyphSource::Smufl } },
    { 195, { "four", 0x34, "", SmuflGlyphSource::Smufl } },
    { 196, { "five", 0x35, "", SmuflGlyphSource::Smufl } },
    { 197, { "six", 0x36, "", SmuflGlyphSource::Smufl } },
    { 198, { "seven", 0x37, "", SmuflGlyphSource::Smufl } },
    { 199, { "eight", 0x38, "", SmuflGlyphSource::Smufl } },
    { 200, { "nine", 0x39, "", SmuflGlyphSource::Smufl } },
    { 210, { "quotedblleft", 0x201C, "", SmuflGlyphSource::Smufl } },
    { 211, { "quotedblright", 0x201D, "", SmuflGlyphSource::Smufl } },
    { 212, { "quoteLeft", 0x2018, "", SmuflGlyphSource::Smufl } },
    { 213, { "quoteRight", 0x2019, "", SmuflGlyphSource::Smufl } },
    { 215, { "noteheadXBlack", 0xE0A9, "", SmuflGlyphSource::Smufl } },
    { 245, { "coda", 0xE048, "", SmuflGlyphSource::Smufl } },
    { 246, { "segno", 0xE047, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
