// This file is generated from Broadway Copyist Text Ext.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> broadwayCopyistTextExtLegacyGlyphs[] = {
    {  94, { "enclosureClosed", 0xF74A, "", SmuflGlyphSource::Finale } },
    { 123, { "csymParensLeftTall", 0xE875, "", SmuflGlyphSource::Smufl } },
    { 124, { "csymHalfDiminished", 0xE871, "", SmuflGlyphSource::Smufl } },
    { 125, { "csymParensRightTall", 0xE876, "", SmuflGlyphSource::Smufl } },
    { 247, { "colon", 0x3A, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
