// This file is generated from Crescendo.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> crescendoLegacyGlyphs[] = {
    {  82, { "harpPedalRaised", 0xE680, "", SmuflGlyphSource::Smufl } },
    { 114, { "harpPedalCentered", 0xE681, "", SmuflGlyphSource::Smufl } },
    { 168, { "harpPedalLowered", 0xE682, "", SmuflGlyphSource::Smufl } },
    { 229, { "harpPedalDivider", 0xE683, "", SmuflGlyphSource::Smufl } },
    { 243, { "pluckedSnapPizzicatoAbove", 0xE631, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
