// This file is generated from Engraver Time.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> engraverTimeLegacyGlyphs[] = {
    {  48, { "timeSig0Large", 0xF440, "", SmuflGlyphSource::Finale, true } },
    {  49, { "timeSig1Large", 0xF441, "", SmuflGlyphSource::Finale, true } },
    {  50, { "timeSig2Large", 0xF442, "", SmuflGlyphSource::Finale, true } },
    {  51, { "timeSig3Large", 0xF443, "", SmuflGlyphSource::Finale, true } },
    {  52, { "timeSig4Large", 0xF444, "", SmuflGlyphSource::Finale, true } },
    {  53, { "timeSig5Large", 0xF445, "", SmuflGlyphSource::Finale, true } },
    {  54, { "timeSig6Large", 0xF446, "", SmuflGlyphSource::Finale, true } },
    {  55, { "timeSig7Large", 0xF447, "", SmuflGlyphSource::Finale, true } },
    {  56, { "timeSig8Large", 0xF448, "", SmuflGlyphSource::Finale, true } },
    {  57, { "timeSig9Large", 0xF449, "", SmuflGlyphSource::Finale, true } },
};

} // namespace smufl_mapping::detail::legacy
