// This file is generated from Engraver Text H.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> engraverTextHLegacyGlyphs[] = {
    {  45, { "articTenutoAbove", 0xE4A4, "", SmuflGlyphSource::Smufl } },
    {  46, { "articStaccatoAbove", 0xE4A2, "", SmuflGlyphSource::Smufl } },
    {  62, { "articAccentAbove", 0xE4A0, "", SmuflGlyphSource::Smufl } },
    {  72, { "arpeggioArrowUpShort", 0xF770, "", SmuflGlyphSource::Finale } },
    {  73, { "arpeggioArrowUpMedium", 0xF771, "", SmuflGlyphSource::Finale } },
    {  74, { "arpeggioArrowUpLong", 0xF772, "", SmuflGlyphSource::Finale } },
    {  75, { "arpeggioArrowDownShort", 0xF773, "", SmuflGlyphSource::Finale } },
    {  76, { "arpeggioArrowDownMedium", 0xF774, "", SmuflGlyphSource::Finale } },
    {  77, { "arpeggioArrowDownLong", 0xF775, "", SmuflGlyphSource::Finale } },
    {  79, { "harpPedalCentered", 0xE681, "", SmuflGlyphSource::Smufl } },
    {  80, { "harpPedalDivider", 0xE683, "", SmuflGlyphSource::Smufl } },
    {  82, { "csymBracketRightTall", 0xE878, "", SmuflGlyphSource::Smufl } },
    {  84, { "arrowheadBlackDown", 0xEB7C, "", SmuflGlyphSource::Smufl } },
    {  85, { "arrowUpShort", 0xF776, "", SmuflGlyphSource::Finale } },
    {  86, { "arrowUpMedium", 0xF777, "", SmuflGlyphSource::Finale } },
    {  87, { "arrowUpLong", 0xF778, "", SmuflGlyphSource::Finale } },
    {  88, { "arrowDownShort", 0xF779, "", SmuflGlyphSource::Finale } },
    {  89, { "arrowDownMedium", 0xF77A, "", SmuflGlyphSource::Finale } },
    {  90, { "arrowDownLong", 0xF77B, "", SmuflGlyphSource::Finale } },
    {  92, { "metricModulationArrowLeft", 0xEC63, "", SmuflGlyphSource::Smufl } },
    {  96, { "quindicesimaBassaMb", 0xE51D, "", SmuflGlyphSource::Smufl } },
    {  98, { "noteDoubleWholeSquare", 0xE1D1, "", SmuflGlyphSource::Smufl } },
    { 101, { "metNote8thUp", 0xECA7, "", SmuflGlyphSource::Smufl } },
    { 103, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl } },
    { 104, { "metNoteHalfUp", 0xECA3, "", SmuflGlyphSource::Smufl } },
    { 110, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl } },
    { 111, { "harpPedalRaised", 0xE680, "", SmuflGlyphSource::Smufl } },
    { 112, { "harpPedalLowered", 0xE682, "", SmuflGlyphSource::Smufl } },
    { 113, { "metNoteQuarterUp", 0xECA5, "", SmuflGlyphSource::Smufl } },
    { 114, { "csymBracketLeftTall", 0xE877, "", SmuflGlyphSource::Smufl } },
    { 115, { "accidentalSharp", 0xE262, "", SmuflGlyphSource::Smufl } },
    { 116, { "arrowheadBlackUp", 0xEB78, "", SmuflGlyphSource::Smufl } },
    { 117, { "noteDoubleWhole", 0xECA0, "", SmuflGlyphSource::Smufl } },
    { 118, { "metNoteDoubleWhole", 0xECA0, "", SmuflGlyphSource::Smufl } },
    { 119, { "metNoteWhole", 0xECA2, "", SmuflGlyphSource::Smufl } },
    { 120, { "metNote16thUp", 0xECA9, "", SmuflGlyphSource::Smufl } },
    { 123, { "timeSigParensLeft", 0xE094, "", SmuflGlyphSource::Smufl } },
    { 124, { "metricModulationArrowRight", 0xEC64, "", SmuflGlyphSource::Smufl } },
    { 125, { "timeSigParensRight", 0xE095, "", SmuflGlyphSource::Smufl } },
    { 195, { "ottavaBassa", 0xE512, "", SmuflGlyphSource::Smufl } },
    { 215, { "ottavaBassaVb", 0xE51C, "", SmuflGlyphSource::Smufl } },
    { 219, { "quindicesimaBassa", 0xE516, "", SmuflGlyphSource::Smufl } },
    { 227, { "ottavaBassaBa", 0xE513, "", SmuflGlyphSource::Smufl } },
    { 235, { "metAugmentationDot", 0xECB7, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
