// This file is generated from Finale AlphaNotes.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> finaleAlphanotesLegacyGlyphs[] = {
    {  33, { "noteReWhole", 0xE151, "", SmuflGlyphSource::Smufl } },
    {  34, { "noteMiWhole", 0xE152, "", SmuflGlyphSource::Smufl } },
    {  35, { "noteSoWhole", 0xE154, "", SmuflGlyphSource::Smufl } },
    {  36, { "noteLaWhole", 0xE155, "", SmuflGlyphSource::Smufl } },
    {  37, { "noteTiWhole", 0xE156, "", SmuflGlyphSource::Smufl } },
    {  38, { "noteReHalf", 0xE159, "", SmuflGlyphSource::Smufl } },
    {  39, { "noteMiHalf", 0xE15A, "", SmuflGlyphSource::Smufl } },
    {  40, { "noteSoHalf", 0xE15C, "", SmuflGlyphSource::Smufl } },
    {  41, { "noteLaHalf", 0xE15D, "", SmuflGlyphSource::Smufl } },
    {  42, { "noteTiHalf", 0xE15E, "", SmuflGlyphSource::Smufl } },
    {  43, { "noteReBlack", 0xE161, "", SmuflGlyphSource::Smufl } },
    {  44, { "noteMiBlack", 0xE162, "", SmuflGlyphSource::Smufl } },
    {  45, { "noteSoBlack", 0xE164, "", SmuflGlyphSource::Smufl } },
    {  46, { "noteLaBlack", 0xE165, "", SmuflGlyphSource::Smufl } },
    {  47, { "noteTiBlack", 0xE166, "", SmuflGlyphSource::Smufl } },
    {  48, { "noteAWhole", 0xE169, "", SmuflGlyphSource::Smufl } },
    {  49, { "noteASharpWhole", 0xE16A, "", SmuflGlyphSource::Smufl } },
    {  50, { "noteAFlatWhole", 0xE168, "", SmuflGlyphSource::Smufl } },
    {  51, { "noteBWhole", 0xE16C, "", SmuflGlyphSource::Smufl } },
    {  52, { "noteBSharpWhole", 0xE16D, "", SmuflGlyphSource::Smufl } },
    {  53, { "noteBFlatWhole", 0xE16B, "", SmuflGlyphSource::Smufl } },
    {  54, { "noteCWhole", 0xE16F, "", SmuflGlyphSource::Smufl } },
    {  55, { "noteCSharpWhole", 0xE170, "", SmuflGlyphSource::Smufl } },
    {  56, { "noteCFlatWhole", 0xE16E, "", SmuflGlyphSource::Smufl } },
    {  57, { "noteDWhole", 0xE172, "", SmuflGlyphSource::Smufl } },
    {  58, { "noteDSharpWhole", 0xE173, "", SmuflGlyphSource::Smufl } },
    {  59, { "noteDFlatWhole", 0xE171, "", SmuflGlyphSource::Smufl } },
    {  60, { "noteEWhole", 0xE175, "", SmuflGlyphSource::Smufl } },
    {  61, { "noteESharpWhole", 0xE176, "", SmuflGlyphSource::Smufl } },
    {  62, { "noteEFlatWhole", 0xE174, "", SmuflGlyphSource::Smufl } },
    {  63, { "noteFWhole", 0xE178, "", SmuflGlyphSource::Smufl } },
    {  64, { "noteFSharpWhole", 0xE179, "", SmuflGlyphSource::Smufl } },
    {  65, { "noteFFlatWhole", 0xE177, "", SmuflGlyphSource::Smufl } },
    {  66, { "noteGWhole", 0xE17B, "", SmuflGlyphSource::Smufl } },
    {  67, { "noteGSharpWhole", 0xE17C, "", SmuflGlyphSource::Smufl } },
    {  68, { "noteGFlatWhole", 0xE17A, "", SmuflGlyphSource::Smufl } },
    {  69, { "noteAHalf", 0xE180, "", SmuflGlyphSource::Smufl } },
    {  70, { "noteASharpHalf", 0xE181, "", SmuflGlyphSource::Smufl } },
    {  71, { "noteAFlatHalf", 0xE17F, "", SmuflGlyphSource::Smufl } },
    {  72, { "noteBHalf", 0xE183, "", SmuflGlyphSource::Smufl } },
    {  73, { "noteBSharpHalf", 0xE184, "", SmuflGlyphSource::Smufl } },
    {  74, { "noteBFlatHalf", 0xE182, "", SmuflGlyphSource::Smufl } },
    {  75, { "noteCHalf", 0xE186, "", SmuflGlyphSource::Smufl } },
    {  76, { "noteCSharpHalf", 0xE187, "", SmuflGlyphSource::Smufl } },
    {  77, { "noteCFlatHalf", 0xE185, "", SmuflGlyphSource::Smufl } },
    {  78, { "noteDHalf", 0xE189, "", SmuflGlyphSource::Smufl } },
    {  79, { "noteDSharpHalf", 0xE18A, "", SmuflGlyphSource::Smufl } },
    {  80, { "noteDFlatHalf", 0xE188, "", SmuflGlyphSource::Smufl } },
    {  81, { "noteEHalf", 0xE18C, "", SmuflGlyphSource::Smufl } },
    {  82, { "noteESharpHalf", 0xE18D, "", SmuflGlyphSource::Smufl } },
    {  83, { "noteEFlatHalf", 0xE18B, "", SmuflGlyphSource::Smufl } },
    {  84, { "noteFHalf", 0xE18F, "", SmuflGlyphSource::Smufl } },
    {  85, { "noteFSharpHalf", 0xE190, "", SmuflGlyphSource::Smufl } },
    {  86, { "noteFFlatHalf", 0xE18E, "", SmuflGlyphSource::Smufl } },
    {  87, { "noteGHalf", 0xE192, "", SmuflGlyphSource::Smufl } },
    {  88, { "noteGSharpHalf", 0xE193, "", SmuflGlyphSource::Smufl } },
    {  89, { "noteGFlatHalf", 0xE191, "", SmuflGlyphSource::Smufl } },
    {  90, { "noteHBlack", 0xE1AB, "", SmuflGlyphSource::Smufl } },
    {  91, { "noteHHalf", 0xE194, "", SmuflGlyphSource::Smufl } },
    {  92, { "noteHWhole", 0xE17D, "", SmuflGlyphSource::Smufl } },
    {  97, { "noteABlack", 0xE197, "", SmuflGlyphSource::Smufl } },
    {  98, { "noteASharpBlack", 0xE198, "", SmuflGlyphSource::Smufl } },
    {  99, { "noteAFlatBlack", 0xE196, "", SmuflGlyphSource::Smufl } },
    { 100, { "noteBBlack", 0xE19A, "", SmuflGlyphSource::Smufl } },
    { 101, { "noteBSharpBlack", 0xE19B, "", SmuflGlyphSource::Smufl } },
    { 102, { "noteBFlatBlack", 0xE199, "", SmuflGlyphSource::Smufl } },
    { 103, { "noteCBlack", 0xE19D, "", SmuflGlyphSource::Smufl } },
    { 104, { "noteCSharpBlack", 0xE19E, "", SmuflGlyphSource::Smufl } },
    { 105, { "noteCFlatBlack", 0xE19C, "", SmuflGlyphSource::Smufl } },
    { 106, { "noteDBlack", 0xE1A0, "", SmuflGlyphSource::Smufl } },
    { 107, { "noteDSharpBlack", 0xE1A1, "", SmuflGlyphSource::Smufl } },
    { 108, { "noteDFlatBlack", 0xE19F, "", SmuflGlyphSource::Smufl } },
    { 109, { "noteEBlack", 0xE1A3, "", SmuflGlyphSource::Smufl } },
    { 110, { "noteESharpBlack", 0xE1A4, "", SmuflGlyphSource::Smufl } },
    { 111, { "noteEFlatBlack", 0xE1A2, "", SmuflGlyphSource::Smufl } },
    { 112, { "noteFBlack", 0xE1A6, "", SmuflGlyphSource::Smufl } },
    { 113, { "noteFSharpBlack", 0xE1A7, "", SmuflGlyphSource::Smufl } },
    { 114, { "noteFFlatBlack", 0xE1A5, "", SmuflGlyphSource::Smufl } },
    { 115, { "noteGBlack", 0xE1A9, "", SmuflGlyphSource::Smufl } },
    { 116, { "noteGSharpBlack", 0xE1AA, "", SmuflGlyphSource::Smufl } },
    { 117, { "noteGFlatBlack", 0xE1A8, "", SmuflGlyphSource::Smufl } },
    { 119, { "noteEmptyWhole", 0xE1AD, "", SmuflGlyphSource::Smufl } },
    { 207, { "noteEmptyBlack", 0xE1AF, "", SmuflGlyphSource::Smufl } },
    { 250, { "noteEmptyHalf", 0xE1AE, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
