// This file is generated from Finale Copyist Text.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> finaleCopyistTextLegacyGlyphs[] = {
    {  91, { "enclosureParenOverLeft", 0xF723, "", SmuflGlyphSource::Finale, false } },
    {  92, { "enclosureParenOverExtension", 0xF724, "", SmuflGlyphSource::Finale, false } },
    {  93, { "enclosureParenOverRight", 0xF725, "", SmuflGlyphSource::Finale, false } },
    {  94, { "enclosureParenOverExtensionLong", 0xF726, "", SmuflGlyphSource::Finale, false } },
    {  95, { "enclosureBracketExtensionShort", 0xF727, "", SmuflGlyphSource::Finale, false } },
    {  96, { "csymDiminished", 0xE870, "", SmuflGlyphSource::Smufl, false } },
    { 123, { "enclosureBracketLeft", 0xF720, "", SmuflGlyphSource::Finale, false } },
    { 124, { "enclosureBracketExtension", 0xF721, "", SmuflGlyphSource::Finale, false } },
    { 125, { "enclosureBracketRight", 0xF722, "", SmuflGlyphSource::Finale, false } },
    { 126, { "enclosureClosed", 0xF74A, "", SmuflGlyphSource::Finale, false } },
    { 162, { "enclosureParenUnderlineRightShortAlt2", 0xF749, "", SmuflGlyphSource::Finale, false } },
    { 165, { "enclosureParenOverRight2Long", 0xF746, "", SmuflGlyphSource::Finale, false } },
    { 176, { "enclosureParenUnderlineExtensionAlt", 0xF748, "", SmuflGlyphSource::Finale, false } },
    { 177, { "enclosureParenOverRight2Alt", 0xF743, "", SmuflGlyphSource::Finale, false } },
    { 196, { "enclosureBracketLeftLong", 0xF729, "", SmuflGlyphSource::Finale, false } },
    { 197, { "enclosureBracketLongExtension", 0xF72A, "", SmuflGlyphSource::Finale, false } },
    { 198, { "enclosureBracketRightLong", 0xF72B, "", SmuflGlyphSource::Finale, false } },
    { 200, { "textEnclosureFine", 0xF81F, "", SmuflGlyphSource::Finale, false } },
    { 201, { "textEnclosureCurvedArrow", 0xF814, "", SmuflGlyphSource::Finale, false } },
    { 202, { "textEnclosureSegmentCUrvedArrowShort", 0xF819, "", SmuflGlyphSource::Finale, false } },
    { 203, { "textEnclosureSegmentArrowJogUp", 0xF81B, "", SmuflGlyphSource::Finale, false } },
    { 204, { "textEnclosureSegmentArrowJogOver", 0xF81C, "", SmuflGlyphSource::Finale, false } },
    { 205, { "textEnclosureSegmentArrowJogDown", 0xF81D, "", SmuflGlyphSource::Finale, false } },
    { 206, { "textEnclosureCurvedArrowWHook", 0xF815, "", SmuflGlyphSource::Finale, false } },
    { 207, { "textEnclosureSegmentArrowDown", 0xF81E, "", SmuflGlyphSource::Finale, false } },
    { 209, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl, false } },
    { 210, { "textEnclosureSegmentLeftHook", 0xF816, "", SmuflGlyphSource::Finale, false } },
    { 211, { "textEnclosureExtensionShort", 0xF817, "", SmuflGlyphSource::Finale, false } },
    { 212, { "textEnclosureSegmentCUrvedArrowShort", 0xF819, "", SmuflGlyphSource::Finale, false } },
    { 214, { "textEnclosureSegmentCUrvedArrowShort", 0xF744, "", SmuflGlyphSource::Finale, true } },
    { 216, { "enclosureParenOverLeft2Alt", 0xF741, "", SmuflGlyphSource::Finale, false } },
    { 217, { "textEnclosureSegmentExtensionLong", 0xF818, "", SmuflGlyphSource::Finale, false } },
    { 224, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl, false } },
    { 226, { "metNote8thUp", 0xECA7, "", SmuflGlyphSource::Smufl, false } },
    { 227, { "metNoteQuarterUp", 0xECA5, "", SmuflGlyphSource::Smufl, false } },
    { 228, { "metNote16thUp", 0xECA9, "", SmuflGlyphSource::Smufl, false } },
    { 229, { "metNoteQuarterUp", 0xECA5, "", SmuflGlyphSource::Smufl, false } },
    { 231, { "metNoteHalfUp", 0xECA3, "", SmuflGlyphSource::Smufl, false } },
    { 232, { "enclosureBracketExtensionLong", 0xF73C, "", SmuflGlyphSource::Finale, false } },
    { 233, { "metNoteWhole", 0xECA2, "", SmuflGlyphSource::Smufl, false } },
    { 234, { "csymParensLeftTall", 0xE875, "", SmuflGlyphSource::Smufl, false } },
    { 235, { "csymParensRightTall", 0xE876, "", SmuflGlyphSource::Smufl, false } },
    { 236, { "textEnclosureExtensionShort", 0xF817, "", SmuflGlyphSource::Finale, false } },
    { 237, { "enclosureParenOverLeft2Alt", 0xF723, "", SmuflGlyphSource::Finale, true } },
    { 238, { "enclosureParenUnderlineExtensionAlt", 0xF748, "", SmuflGlyphSource::Finale, false } },
    { 239, { "enclosureParenUnderlineRight", 0xF731, "", SmuflGlyphSource::Finale, false } },
    { 241, { "onehalf", 0xBD, "", SmuflGlyphSource::Smufl, false } },
    { 242, { "x", 0x78, "", SmuflGlyphSource::Smufl, false } },
    { 243, { "coda", 0xE048, "", SmuflGlyphSource::Smufl, false } },
    { 245, { "textEnclosureSegmentJogUp", 0xF811, "", SmuflGlyphSource::Finale, false } },
    { 246, { "textEnclosureSegmentJogDown", 0xF810, "", SmuflGlyphSource::Finale, false } },
    { 248, { "textEnclosureSegmentExtension", 0xF812, "", SmuflGlyphSource::Finale, false } },
    { 249, { "enclosureParenUnderlineLeftAlt2", 0xF747, "", SmuflGlyphSource::Finale, false } },
    { 250, { "textEnclosureSegmentArrow", 0xF813, "", SmuflGlyphSource::Finale, false } },
    { 251, { "enclosureParenUnderlineExtensionAlt", 0xF748, "", SmuflGlyphSource::Finale, false } },
    { 252, { "enclosureParenUnderlineRightShortAlt2", 0xF749, "", SmuflGlyphSource::Finale, false } },
};

} // namespace smufl_mapping::detail::legacy
