// This file is generated from Finale Numerics.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> finaleNumericsLegacyGlyphs[] = {
    {  43, { "figbassPlus", 0xEA6C, "", SmuflGlyphSource::Smufl } },
    {  45, { "functionMinus", 0xEA7B, "", SmuflGlyphSource::Smufl } },
    {  47, { "csymAlteredBassSlash", 0xE87B, "", SmuflGlyphSource::Smufl } },
    {  53, { "figbass5", 0xEA57, "", SmuflGlyphSource::Smufl } },
    {  64, { "figbass2", 0xEA52, "", SmuflGlyphSource::Smufl } },
    {  73, { "functionIUpper", 0xEA9A, "", SmuflGlyphSource::Smufl } },
    {  78, { "functionNUpper", 0xEA85, "", SmuflGlyphSource::Smufl } },
    {  80, { "functionPUpper", 0xEA87, "", SmuflGlyphSource::Smufl } },
    {  86, { "functionVUpper", 0xEA8D, "", SmuflGlyphSource::Smufl } },
    { 105, { "functionILower", 0xEA9B, "", SmuflGlyphSource::Smufl } },
    { 106, { "csymHalfDiminished", 0xE871, "", SmuflGlyphSource::Smufl } },
    { 107, { "csymDiminished", 0xE870, "", SmuflGlyphSource::Smufl } },
    { 108, { "csymAugmented", 0xE872, "", SmuflGlyphSource::Smufl } },
    { 114, { "functionRLower", 0xED03, "", SmuflGlyphSource::Smufl } },
    { 116, { "functionTLower", 0xEA8C, "", SmuflGlyphSource::Smufl } },
    { 118, { "functionVLower", 0xEA8E, "", SmuflGlyphSource::Smufl } },
    { 120, { "figbassSharp", 0xEA66, "", SmuflGlyphSource::Smufl } },
    { 121, { "figbassNatural", 0xEA65, "", SmuflGlyphSource::Smufl } },
    { 122, { "figbassFlat", 0xEA64, "", SmuflGlyphSource::Smufl } },
    { 161, { "figbass1", 0xEA51, "", SmuflGlyphSource::Smufl } },
    { 162, { "figbass4", 0xEA55, "", SmuflGlyphSource::Smufl } },
    { 163, { "figbass3", 0xEA54, "", SmuflGlyphSource::Smufl } },
    { 167, { "figbass6", 0xEA5B, "", SmuflGlyphSource::Smufl } },
    { 169, { "figbassBracketLeft", 0xEA68, "", SmuflGlyphSource::Smufl } },
    { 174, { "csymParensLeftVeryTall", 0xE879, "", SmuflGlyphSource::Smufl } },
    { 176, { "figbass8", 0xEA60, "", SmuflGlyphSource::Smufl } },
    { 177, { "functionMUpper", 0xED00, "", SmuflGlyphSource::Smufl } },
    { 181, { "csymMinor", 0xE874, "", SmuflGlyphSource::Smufl } },
    { 182, { "figbass7", 0xEA5D, "", SmuflGlyphSource::Smufl } },
    { 183, { "figbass9", 0xEA61, "", SmuflGlyphSource::Smufl } },
    { 186, { "figbass0", 0xEA50, "", SmuflGlyphSource::Smufl } },
    { 199, { "figbassParensRight", 0xEA6B, "", SmuflGlyphSource::Smufl } },
    { 203, { "functionMLower", 0xED01, "", SmuflGlyphSource::Smufl } },
    { 205, { "csymBracketRightTall", 0xE878, "", SmuflGlyphSource::Smufl } },
    { 207, { "figbassBracketRight", 0xEA69, "", SmuflGlyphSource::Smufl } },
    { 210, { "figbassDoubleFlat", 0xEA63, "", SmuflGlyphSource::Smufl } },
    { 212, { "figbassDoubleSharp", 0xEA67, "", SmuflGlyphSource::Smufl } },
    { 216, { "csymParensRightTall", 0xE876, "", SmuflGlyphSource::Smufl } },
    { 223, { "figbassCombiningRaising", 0xEA6D, "", SmuflGlyphSource::Smufl } },
    { 230, { "arrowheadOpenRight", 0xEB8A, "", SmuflGlyphSource::Smufl } },
    { 231, { "figbassParensLeft", 0xEA6A, "", SmuflGlyphSource::Smufl } },
    { 242, { "figbass2Raised", 0xEA53, "", SmuflGlyphSource::Smufl } },
    { 245, { "figbass5Raised1", 0xEA58, "", SmuflGlyphSource::Smufl } },
    { 246, { "figbass4Raised", 0xEA56, "", SmuflGlyphSource::Smufl } },
    { 248, { "csymParensLeftTall", 0xE875, "", SmuflGlyphSource::Smufl } },
    { 249, { "figbass7Raised1", 0xEA5E, "", SmuflGlyphSource::Smufl } },
    { 250, { "figbass6Raised", 0xEA5C, "", SmuflGlyphSource::Smufl } },
    { 252, { "figbass9Raised", 0xEA62, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
