// This file is generated from Finale Copyist Text Ext.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> finaleCopyistTextExtLegacyGlyphs[] = {
    {  94, { "enclosureClosed", 0xF74A, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
