// This file is generated from Finale Mallets.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> finaleMalletsLegacyGlyphs[] = {
    {  33, { "pictBeaterSoftTimpaniRight", 0xE78A, "", SmuflGlyphSource::Smufl } },
    {  35, { "pictBeaterHardTimpaniRight", 0xE792, "", SmuflGlyphSource::Smufl } },
    {  36, { "pictBeaterWoodTimpaniRight", 0xE796, "", SmuflGlyphSource::Smufl } },
    {  37, { "pictBeaterSoftXylophoneRight", 0xE772, "", SmuflGlyphSource::Smufl } },
    {  38, { "pictBeaterHardXylophoneRight", 0xE77A, "", SmuflGlyphSource::Smufl } },
    {  40, { "pictBeaterSoftYarnRight", 0xE7A4, "", SmuflGlyphSource::Smufl } },
    {  41, { "pictBeaterMediumYarnRight", 0xE7A8, "", SmuflGlyphSource::Smufl } },
    {  42, { "pictBeaterWoodXylophoneRight", 0xE77E, "", SmuflGlyphSource::Smufl } },
    {  43, { "noteheadPlusBlack", 0xE0AF, "", SmuflGlyphSource::Smufl } },
    {  48, { "pictBeaterMediumYarnLeft", 0xE7A9, "", SmuflGlyphSource::Smufl } },
    {  49, { "pictBeaterSoftTimpaniLeft", 0xE78B, "", SmuflGlyphSource::Smufl } },
    {  50, { "pictBeaterMediumTimpaniLeft", 0xE78F, "", SmuflGlyphSource::Smufl } },
    {  51, { "pictBeaterHardTimpaniLeft", 0xE793, "", SmuflGlyphSource::Smufl } },
    {  52, { "pictBeaterWoodTimpaniLeft", 0xE797, "", SmuflGlyphSource::Smufl } },
    {  53, { "pictBeaterSoftXylophoneLeft", 0xE773, "", SmuflGlyphSource::Smufl } },
    {  54, { "pictBeaterMediumXylophoneLeft", 0xE777, "", SmuflGlyphSource::Smufl } },
    {  55, { "pictBeaterHardXylophoneLeft", 0xE77B, "", SmuflGlyphSource::Smufl } },
    {  56, { "pictBeaterWoodXylophoneLeft", 0xE77F, "", SmuflGlyphSource::Smufl } },
    {  57, { "pictBeaterSoftYarnLeft", 0xE7A5, "", SmuflGlyphSource::Smufl } },
    {  58, { "pictBeaterHardYarnRight", 0xE7AC, "", SmuflGlyphSource::Smufl } },
    {  59, { "pictBeaterHardYarnLeft", 0xE7AD, "", SmuflGlyphSource::Smufl } },
    {  64, { "pictBeaterMediumTimpaniRight", 0xE78E, "", SmuflGlyphSource::Smufl } },
    {  65, { "pictBeaterSoftBassDrumDown", 0xE799, "", SmuflGlyphSource::Smufl } },
    {  66, { "pictBeaterTrianglePlain", 0xE7EF, "", SmuflGlyphSource::Smufl } },
    {  67, { "pictBeaterSpoonWoodenMallet", 0xE7DC, "", SmuflGlyphSource::Smufl } },
    {  68, { "pictBeaterHardBassDrumDown", 0xE79D, "", SmuflGlyphSource::Smufl } },
    {  69, { "pictBeaterHardTimpaniDown", 0xE791, "", SmuflGlyphSource::Smufl } },
    {  70, { "pictBeaterDoubleBassDrumDown", 0xE7A1, "", SmuflGlyphSource::Smufl } },
    {  71, { "pictBeaterSnareSticksDown", 0xE7D2, "", SmuflGlyphSource::Smufl } },
    {  72, { "pictBeaterJazzSticksDown", 0xE7D4, "", SmuflGlyphSource::Smufl } },
    {  73, { "pictBeaterWoodXylophoneDown", 0xE77D, "", SmuflGlyphSource::Smufl } },
    {  74, { "pictBeaterBrassMalletsDown", 0xE7DA, "", SmuflGlyphSource::Smufl } },
    {  75, { "pictBeaterMalletDown", 0xE7EC, "", SmuflGlyphSource::Smufl } },
    {  76, { "pictBeaterGuiroScraper", 0xE7DD, "", SmuflGlyphSource::Smufl } },
    {  77, { "pictBeaterWireBrushesDown", 0xE7D8, "", SmuflGlyphSource::Smufl } },
    {  78, { "pictBeaterBrassMalletsRight", 0xE7ED, "", SmuflGlyphSource::Smufl } },
    {  79, { "pictBeaterSoftYarnDown", 0xE7A3, "", SmuflGlyphSource::Smufl } },
    {  80, { "pictBeaterMediumYarnDown", 0xE7A7, "", SmuflGlyphSource::Smufl } },
    {  81, { "pictBeaterSoftTimpaniDown", 0xE789, "", SmuflGlyphSource::Smufl } },
    {  82, { "pictBeaterWoodTimpaniDown", 0xE795, "", SmuflGlyphSource::Smufl } },
    {  83, { "pictBeaterMediumBassDrumDown", 0xE79B, "", SmuflGlyphSource::Smufl } },
    {  84, { "pictBeaterSoftXylophoneDown", 0xE771, "", SmuflGlyphSource::Smufl } },
    {  85, { "pictBeaterHardXylophoneDown", 0xE779, "", SmuflGlyphSource::Smufl } },
    {  87, { "pictBeaterMediumTimpaniDown", 0xE78D, "", SmuflGlyphSource::Smufl } },
    {  88, { "pictBeaterMetalHammer", 0xE7E0, "", SmuflGlyphSource::Smufl } },
    {  89, { "pictBeaterMediumXylophoneDown", 0xE775, "", SmuflGlyphSource::Smufl } },
    {  90, { "pictBeaterKnittingNeedle", 0xE7E2, "", SmuflGlyphSource::Smufl } },
    {  91, { "pictBeaterHardYarnUp", 0xE7AA, "", SmuflGlyphSource::Smufl } },
    {  92, { "pictBeaterFinger", 0xE7E4, "", SmuflGlyphSource::Smufl } },
    {  93, { "pictBeaterHand", 0xE7E3, "", SmuflGlyphSource::Smufl } },
    {  94, { "pictBeaterMediumXylophoneRight", 0xE776, "", SmuflGlyphSource::Smufl } },
    {  97, { "pictBeaterSoftBassDrumUp", 0xE798, "", SmuflGlyphSource::Smufl } },
    { 100, { "pictBeaterHardBassDrumUp", 0xE79C, "", SmuflGlyphSource::Smufl } },
    { 101, { "pictBeaterHardTimpaniUp", 0xE790, "", SmuflGlyphSource::Smufl } },
    { 102, { "pictBeaterDoubleBassDrumUp", 0xE7A0, "", SmuflGlyphSource::Smufl } },
    { 103, { "pictBeaterSnareSticksUp", 0xE7D1, "", SmuflGlyphSource::Smufl } },
    { 104, { "pictBeaterJazzSticksUp", 0xE7D3, "", SmuflGlyphSource::Smufl } },
    { 105, { "pictBeaterWoodXylophoneUp", 0xE77C, "", SmuflGlyphSource::Smufl } },
    { 106, { "pictBeaterBrassMalletsUp", 0xE7D9, "", SmuflGlyphSource::Smufl } },
    { 107, { "pictBeaterMallet", 0xE7DF, "", SmuflGlyphSource::Smufl } },
    { 108, { "pictBeaterTriangleUp", 0xE7D5, "", SmuflGlyphSource::Smufl } },
    { 109, { "pictBeaterWireBrushesUp", 0xE7D7, "", SmuflGlyphSource::Smufl } },
    { 110, { "pictBeaterBrassMalletsLeft", 0xE7EE, "", SmuflGlyphSource::Smufl } },
    { 111, { "pictBeaterSoftYarnUp", 0xE7A2, "", SmuflGlyphSource::Smufl } },
    { 112, { "pictBeaterMediumYarnUp", 0xE7A6, "", SmuflGlyphSource::Smufl } },
    { 113, { "pictBeaterSoftTimpaniUp", 0xE788, "", SmuflGlyphSource::Smufl } },
    { 114, { "pictBeaterWoodTimpaniUp", 0xE794, "", SmuflGlyphSource::Smufl } },
    { 115, { "pictBeaterMediumBassDrumUp", 0xE79A, "", SmuflGlyphSource::Smufl } },
    { 116, { "pictBeaterSoftXylophoneUp", 0xE770, "", SmuflGlyphSource::Smufl } },
    { 117, { "pictBeaterHardXylophoneUp", 0xE778, "", SmuflGlyphSource::Smufl } },
    { 119, { "pictBeaterMediumTimpaniUp", 0xE78C, "", SmuflGlyphSource::Smufl } },
    { 120, { "pictBeaterHammer", 0xE7E1, "", SmuflGlyphSource::Smufl } },
    { 121, { "pictBeaterMediumXylophoneUp", 0xE774, "", SmuflGlyphSource::Smufl } },
    { 122, { "pictCoins", 0xE7E7, "", SmuflGlyphSource::Smufl } },
    { 123, { "pictBeaterHardYarnDown", 0xE7AB, "", SmuflGlyphSource::Smufl } },
    { 124, { "pictBeaterFingernails", 0xE7E6, "", SmuflGlyphSource::Smufl } },
    { 125, { "pictBeaterFist", 0xE7E5, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
