// This file is generated from GraceNotes.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> gracenotesLegacyGlyphs[] = {
    {  38, { "gClef", 0xE050, "", SmuflGlyphSource::Smufl, false } },
    {  63, { "fClef", 0xE062, "", SmuflGlyphSource::Smufl, false } },
    {  64, { "accidentalQuarterToneSharp4", 0xE47E, "", SmuflGlyphSource::Smufl, false } },
    {  66, { "cClef", 0xE05C, "", SmuflGlyphSource::Smufl, false } },
    {  75, { "cClefFrench20C", 0xF4BF, "", SmuflGlyphSource::Bravura, false } },
    {  86, { "gClef8vb", 0xE052, "", SmuflGlyphSource::Smufl, false } },
    { 124, { "tremolo1", 0xE220, "", SmuflGlyphSource::Smufl, false } },
    { 199, { "tremolo2", 0xE221, "", SmuflGlyphSource::Smufl, false } },
    { 200, { "tremolo3", 0xE222, "", SmuflGlyphSource::Smufl, false } },
    { 230, { "tremolo4", 0xE223, "", SmuflGlyphSource::Smufl, false } },
    { 245, { "accidentalQuarterToneFlat4", 0xE47F, "", SmuflGlyphSource::Smufl, false } },
};

} // namespace smufl_mapping::detail::legacy
