// This file is generated from JazzText Extended.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> jazztextExtendedLegacyGlyphs[] = {
    {  94, { "enclosureParenOverExtensionLong", 0xF726, "", SmuflGlyphSource::Finale } },
    {  96, { "ring", 0x2DA, "", SmuflGlyphSource::Smufl } },
    { 128, { "Adieresis", 0xC4, "", SmuflGlyphSource::Smufl } },
    { 129, { "Aring", 0xC5, "", SmuflGlyphSource::Smufl } },
    { 130, { "Ccedilla", 0xC7, "", SmuflGlyphSource::Smufl } },
    { 131, { "Eacute", 0xC9, "", SmuflGlyphSource::Smufl } },
    { 132, { "Ntilde", 0xD1, "", SmuflGlyphSource::Smufl } },
    { 133, { "Odieresis", 0xD6, "", SmuflGlyphSource::Smufl } },
    { 134, { "Udieresis", 0xDC, "", SmuflGlyphSource::Smufl } },
    { 135, { "aacute", 0xE1, "", SmuflGlyphSource::Smufl } },
    { 136, { "aring", 0xE5, "", SmuflGlyphSource::Smufl } },
    { 137, { "acircumflex", 0xE2, "", SmuflGlyphSource::Smufl } },
    { 138, { "adieresis", 0xE4, "", SmuflGlyphSource::Smufl } },
    { 139, { "atilde", 0xE3, "", SmuflGlyphSource::Smufl } },
    { 140, { "aring", 0xE5, "", SmuflGlyphSource::Smufl } },
    { 141, { "ccedilla", 0xE7, "", SmuflGlyphSource::Smufl } },
    { 142, { "eacute", 0xE9, "", SmuflGlyphSource::Smufl } },
    { 143, { "edieresis", 0xEB, "", SmuflGlyphSource::Smufl } },
    { 144, { "ecircumflex", 0xEA, "", SmuflGlyphSource::Smufl } },
    { 145, { "edieresis", 0xEB, "", SmuflGlyphSource::Smufl } },
    { 146, { "acute", 0xB4, "", SmuflGlyphSource::Smufl } },
    { 147, { "ring", 0x2DA, "", SmuflGlyphSource::Smufl } },
    { 148, { "circumflex", 0x2C6, "", SmuflGlyphSource::Smufl } },
    { 149, { "dieresis", 0xA8, "", SmuflGlyphSource::Smufl } },
    { 150, { "ntilde", 0xF1, "", SmuflGlyphSource::Smufl } },
    { 151, { "oacute", 0xF3, "", SmuflGlyphSource::Smufl } },
    { 152, { "odieresis", 0xF6, "", SmuflGlyphSource::Smufl } },
    { 153, { "ocircumflex", 0xF4, "", SmuflGlyphSource::Smufl } },
    { 154, { "odieresis", 0xF6, "", SmuflGlyphSource::Smufl } },
    { 155, { "otilde", 0xF5, "", SmuflGlyphSource::Smufl } },
    { 156, { "uacute", 0xFA, "", SmuflGlyphSource::Smufl } },
    { 157, { "uring", 0x16F, "", SmuflGlyphSource::Smufl } },
    { 158, { "ucircumflex", 0xFB, "", SmuflGlyphSource::Smufl } },
    { 159, { "udieresis", 0xFC, "", SmuflGlyphSource::Smufl } },
    { 168, { "registered", 0xAE, "", SmuflGlyphSource::Smufl } },
    { 170, { "trademark", 0x2122, "", SmuflGlyphSource::Smufl } },
    { 171, { "acute", 0xB4, "", SmuflGlyphSource::Smufl } },
    { 172, { "dieresis", 0xA8, "", SmuflGlyphSource::Smufl } },
    { 203, { "Aring", 0xC5, "", SmuflGlyphSource::Smufl } },
    { 204, { "Atilde", 0xC3, "", SmuflGlyphSource::Smufl } },
    { 205, { "Otilde", 0xD5, "", SmuflGlyphSource::Smufl } },
    { 210, { "quoteblleft", 0x201C, "", SmuflGlyphSource::Smufl } },
    { 211, { "quoteblright", 0x201D, "", SmuflGlyphSource::Smufl } },
    { 212, { "quoteleft", 0x2018, "", SmuflGlyphSource::Smufl } },
    { 213, { "quoteright", 0x2019, "", SmuflGlyphSource::Smufl } },
    { 216, { "ydieresis", 0xFF, "", SmuflGlyphSource::Smufl } },
    { 217, { "Ydieresis", 0x178, "", SmuflGlyphSource::Smufl } },
    { 225, { "periodcentered", 0x87, "", SmuflGlyphSource::Smufl } },
    { 226, { "quotesinglbase", 0x201A, "", SmuflGlyphSource::Smufl } },
    { 229, { "Acircumflex", 0xC2, "", SmuflGlyphSource::Smufl } },
    { 230, { "Ecircumflex", 0xCA, "", SmuflGlyphSource::Smufl } },
    { 231, { "Aacute", 0xC1, "", SmuflGlyphSource::Smufl } },
    { 232, { "Edieresis", 0xCB, "", SmuflGlyphSource::Smufl } },
    { 233, { "Edieresis", 0xCB, "", SmuflGlyphSource::Smufl } },
    { 234, { "Iacute", 0xCD, "", SmuflGlyphSource::Smufl } },
    { 235, { "Icircumflex", 0xCE, "", SmuflGlyphSource::Smufl } },
    { 236, { "Idieresis", 0xCF, "", SmuflGlyphSource::Smufl } },
    { 237, { "Idieresis", 0xCF, "", SmuflGlyphSource::Smufl } },
    { 238, { "Oacute", 0xD3, "", SmuflGlyphSource::Smufl } },
    { 239, { "Ocircumflex", 0xD4, "", SmuflGlyphSource::Smufl } },
    { 241, { "Odieresis", 0xD6, "", SmuflGlyphSource::Smufl } },
    { 242, { "Uacute", 0xDA, "", SmuflGlyphSource::Smufl } },
    { 243, { "Ucircumflex", 0xDB, "", SmuflGlyphSource::Smufl } },
    { 244, { "Uring", 0x16E, "", SmuflGlyphSource::Smufl } },
    { 246, { "circumflex", 0x2C6, "", SmuflGlyphSource::Smufl } },
    { 247, { "tilde", 0x2DC, "", SmuflGlyphSource::Smufl } },
    { 251, { "ring", 0x2DA, "", SmuflGlyphSource::Smufl } },
    { 252, { "cedilla", 0xB8, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
