// This file is generated from JazzCord.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2025)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> jazzcordLegacyGlyphs[] = {
    {  33, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl } },
    {  34, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl } },
    {  35, { "accidentalSharp", 0xE262, "", SmuflGlyphSource::Smufl } },
    {  43, { "csymAugmented", 0xE872, "", SmuflGlyphSource::Smufl } },
    {  45, { "csymMinor", 0xE874, "", SmuflGlyphSource::Smufl } },
    {  60, { "csymParensLeftTall", 0xE875, "", SmuflGlyphSource::Smufl } },
    {  62, { "csymParensRightTall", 0xE876, "", SmuflGlyphSource::Smufl } },
    {  64, { "csymMajorSeventh", 0xE873, "", SmuflGlyphSource::Smufl } },
    { 181, { "csymDiminished", 0xE870, "", SmuflGlyphSource::Smufl } },
    { 187, { "csymHalfDiminished", 0xE871, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
