// This file is generated from Kousaku Percussion.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> kousakuPercussionLegacyGlyphs[] = {
    {  33, { "noteheadTriangleUpWhite", 0xE0BD, "", SmuflGlyphSource::Smufl } },
    {  35, { "noteheadDiamondWhite", 0xE0DD, "", SmuflGlyphSource::Smufl } },
    {  36, { "noteheadTriangleUpRightWhite", 0xE0C8, "", SmuflGlyphSource::Smufl } },
    {  37, { "noteheadHalf", 0xE0A3, "", SmuflGlyphSource::Smufl } },
    {  38, { "noteheadTriangleRoundDownWhite", 0xE0CC, "", SmuflGlyphSource::Smufl } },
    {  40, { "noteheadTriangleRightWhite", 0xE0C1, "", SmuflGlyphSource::Smufl } },
    {  41, { "noteheadSquareWhite", 0xE0B8, "", SmuflGlyphSource::Smufl } },
    {  42, { "noteheadTriangleLeftWhite", 0xE0BF, "", SmuflGlyphSource::Smufl } },
    {  43, { "noteheadPlusBlack", 0xE0AF, "", SmuflGlyphSource::Smufl } },
    {  45, { "noteheadTriangleDownBlack", 0xE0C7, "", SmuflGlyphSource::Smufl } },
    {  47, { "noteheadSlashVerticalEnds", 0xE100, "", SmuflGlyphSource::Smufl } },
    {  48, { "noteheadSquareBlack", 0xE0B9, "", SmuflGlyphSource::Smufl } },
    {  49, { "noteheadTriangleUpBlack", 0xE0BE, "", SmuflGlyphSource::Smufl } },
    {  50, { "noteheadMoonBlack", 0xE0CB, "", SmuflGlyphSource::Smufl } },
    {  51, { "noteheadDiamondBlack", 0xE0DB, "", SmuflGlyphSource::Smufl } },
    {  52, { "noteheadTriangleUpRightBlack", 0xE0C9, "", SmuflGlyphSource::Smufl } },
    {  53, { "noteheadBlack", 0xE0A4, "", SmuflGlyphSource::Smufl } },
    {  54, { "noteheadSquareBlack", 0xE0B9, "", SmuflGlyphSource::Smufl } },
    {  55, { "noteheadTriangleRoundDownBlack", 0xE0CD, "", SmuflGlyphSource::Smufl } },
    {  56, { "noteheadTriangleLeftBlack", 0xE0C0, "", SmuflGlyphSource::Smufl } },
    {  57, { "noteheadTriangleRightBlack", 0xE0C2, "", SmuflGlyphSource::Smufl } },
    {  63, { "noteheadSlashHorizontalEnds", 0xE101, "", SmuflGlyphSource::Smufl } },
    {  64, { "noteheadMoonWhite", 0xE0CA, "", SmuflGlyphSource::Smufl } },
    {  65, { "accidentalFlatParens", 0xF5D5, "", SmuflGlyphSource::Finale } },
    {  66, { "accidentalQuarterToneFlatStein", 0xE280, "", SmuflGlyphSource::Smufl } },
    {  67, { "fretboard3String", 0xE850, "", SmuflGlyphSource::Smufl } },
    {  68, { "fretboard4String", 0xE852, "", SmuflGlyphSource::Smufl } },
    {  69, { "noteheadHalfParens", 0xF5D2, "", SmuflGlyphSource::Finale } },
    {  70, { "noteheadCircledHalfLarge", 0xE0E9, "", SmuflGlyphSource::Smufl } },
    {  71, { "noteheadSlashedHalf1", 0xE0D1, "", SmuflGlyphSource::Smufl } },
    {  72, { "noteheadSlashedHalf2", 0xE0D2, "", SmuflGlyphSource::Smufl } },
    {  73, { "accidentalFilledReversedFlatAndFlat", 0xE296, "", SmuflGlyphSource::Smufl } },
    {  74, { "accidentalThreeQuarterTonesFlatArrowDown", 0xE271, "", SmuflGlyphSource::Smufl } },
    {  75, { "accidentalQuarterToneFlatNaturalArrowDown", 0xE273, "", SmuflGlyphSource::Smufl } },
    {  76, { "accidentalQuarterToneSharpArrowDown", 0xE275, "", SmuflGlyphSource::Smufl } },
    {  77, { "accidentalDoubleSharp", 0xE263, "", SmuflGlyphSource::Smufl } },
    {  78, { "accidentalNaturalParens", 0xF5D6, "", SmuflGlyphSource::Finale } },
    {  79, { "csymHalfDiminished", 0xE871, "", SmuflGlyphSource::Smufl } },
    {  80, { "pictDamp2", 0xE7FA, "", SmuflGlyphSource::Smufl } },
    {  81, { "pictDamp3", 0xE7FB, "", SmuflGlyphSource::Smufl } },
    {  83, { "flag8thDownStraight", 0xF411, "", SmuflGlyphSource::Finale } },
    {  84, { "noteheadDiamondWhite", 0xE0DD, "", SmuflGlyphSource::Smufl } },
    {  85, { "noteheadSlashWhiteWhole", 0xE102, "", SmuflGlyphSource::Smufl } },
    {  86, { "noteheadDoubleWholeSquare", 0xE0A1, "", SmuflGlyphSource::Smufl } },
    {  87, { "noteheadDoubleWhole", 0xE0A0, "", SmuflGlyphSource::Smufl } },
    {  88, { "noteheadCircleX", 0xE0B3, "", SmuflGlyphSource::Smufl } },
    {  89, { "noteheadCircleX", 0xE0B3, "", SmuflGlyphSource::Smufl } },
    {  90, { "noteheadXOrnateEllipse", 0xE0AB, "", SmuflGlyphSource::Smufl } },
    {  94, { "noteheadSquareWhite", 0xE0B8, "", SmuflGlyphSource::Smufl } },
    {  95, { "noteheadTriangleDownWhite", 0xE0C6, "", SmuflGlyphSource::Smufl } },
    {  97, { "accidentalSharpParens", 0xF5D7, "", SmuflGlyphSource::Finale } },
    {  98, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl } },
    {  99, { "fretboard3StringNut", 0xE851, "", SmuflGlyphSource::Smufl } },
    { 100, { "fretboard4StringNut", 0xE853, "", SmuflGlyphSource::Smufl } },
    { 101, { "noteheadBlackParens", 0xF5D1, "", SmuflGlyphSource::Finale } },
    { 102, { "noteheadCircledBlackLarge", 0xE0E8, "", SmuflGlyphSource::Smufl } },
    { 103, { "noteheadSlashedBlack1", 0xE0CF, "", SmuflGlyphSource::Smufl } },
    { 104, { "noteheadSlashedBlack2", 0xE0D0, "", SmuflGlyphSource::Smufl } },
    { 105, { "accidentalQuarterToneFlatFilledReversed", 0xE480, "", SmuflGlyphSource::Smufl } },
    { 106, { "accidentalQuarterToneFlatArrowUp", 0xE270, "", SmuflGlyphSource::Smufl } },
    { 107, { "accidentalQuarterToneSharpNaturalArrowUp", 0xE272, "", SmuflGlyphSource::Smufl } },
    { 108, { "accidentalThreeQuarterTonesSharpArrowUp", 0xE274, "", SmuflGlyphSource::Smufl } },
    { 109, { "accidentalSharp", 0xE262, "", SmuflGlyphSource::Smufl } },
    { 110, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl } },
    { 111, { "stringsHarmonic", 0xE614, "", SmuflGlyphSource::Smufl } },
    { 112, { "pictHalfOpen2", 0xE7F7, "", SmuflGlyphSource::Smufl } },
    { 113, { "pictDamp4", 0xE7FC, "", SmuflGlyphSource::Smufl } },
    { 114, { "restHalf", 0xE4E4, "", SmuflGlyphSource::Smufl } },
    { 115, { "flag8thUpStraight", 0xF40F, "", SmuflGlyphSource::Finale } },
    { 116, { "noteheadDiamondBlack", 0xE0DB, "", SmuflGlyphSource::Smufl } },
    { 117, { "noteheadSlashDiamondWhite", 0xE104, "", SmuflGlyphSource::Smufl } },
    { 118, { "noteheadDoubleWholeAlt", 0xF40E, "", SmuflGlyphSource::Finale } },
    { 119, { "noteheadWhole", 0xE0A2, "Whole (semibreve) notehead", SmuflGlyphSource::Smufl } },
    { 120, { "noteheadXBlack", 0xE0A9, "", SmuflGlyphSource::Smufl } },
    { 121, { "noteheadXBlack", 0xE0A9, "", SmuflGlyphSource::Smufl } },
    { 122, { "noteheadXOrnate", 0xE0AA, "", SmuflGlyphSource::Smufl } },
    { 129, { "accidentalDoubleSharpParens", 0xF5D8, "", SmuflGlyphSource::Finale } },
    { 140, { "accidentalDoubleFlatParens", 0xF5D9, "", SmuflGlyphSource::Finale } },
    { 181, { "accidentalQuarterToneSharpStein", 0xE282, "", SmuflGlyphSource::Smufl } },
    { 186, { "accidentalDoubleFlat", 0xE264, "", SmuflGlyphSource::Smufl } },
    { 194, { "accidentalQuarterToneSharp4", 0xE47E, "", SmuflGlyphSource::Smufl } },
    { 207, { "noteheadBlack", 0xE0A4, "", SmuflGlyphSource::Smufl } },
    { 245, { "accidentalQuarterToneFlat4", 0xE47F, "", SmuflGlyphSource::Smufl } },
    { 247, { "accidentalThreeQuarterTonesSharpStein", 0xE283, "", SmuflGlyphSource::Smufl } },
    { 250, { "noteheadHalf", 0xE0A3, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
