// This file is generated from MaestroTimes.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> maestrotimesLegacyGlyphs[] = {
    { 165, { "dynamicZ", 0xE525, "", SmuflGlyphSource::Smufl } },
    { 167, { "figbassBracketLeft", 0xEA68, "", SmuflGlyphSource::Smufl } },
    { 170, { "figbassParensLeft", 0xEA6A, "", SmuflGlyphSource::Smufl } },
    { 171, { "dynamicRinforzando", 0xE523, "", SmuflGlyphSource::Smufl } },
    { 172, { "dynamicPPP", 0xE52A, "", SmuflGlyphSource::Smufl } },
    { 175, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl } },
    { 176, { "ottava", 0xE510, "", SmuflGlyphSource::Smufl } },
    { 177, { "csymAugmented", 0xE872, "", SmuflGlyphSource::Smufl } },
    { 181, { "dynamicFFF", 0xE530, "", SmuflGlyphSource::Smufl } },
    { 182, { "figbassBracketRight", 0xEA69, "", SmuflGlyphSource::Smufl } },
    { 183, { "tuplet9", 0xE889, "", SmuflGlyphSource::Smufl } },
    { 184, { "fClef", 0xE062, "", SmuflGlyphSource::Smufl } },
    { 186, { "figbassParensRight", 0xEA6B, "", SmuflGlyphSource::Smufl } },
    { 191, { "metAugmentationDot", 0xECB7, "", SmuflGlyphSource::Smufl } },
    { 193, { "textBlackNoteFrac32ndLongBeam", 0xF7D5, "", SmuflGlyphSource::Finale } },
    { 194, { "textBlackNoteFrac8thLongBeam", 0xF7D3, "", SmuflGlyphSource::Finale } },
    { 197, { "rest16th", 0xE4E7, "", SmuflGlyphSource::Smufl } },
    { 198, { "metricModulationArrowRight", 0xEC64, "", SmuflGlyphSource::Smufl } },
    { 199, { "textTripletBracketFull", 0xF7D2, "", SmuflGlyphSource::Finale } },
    { 200, { "elission", 0x35C, "", SmuflGlyphSource::Smufl } },
    { 202, { "textBlackNoteFrac16thLongBeam", 0xF7D4, "", SmuflGlyphSource::Finale } },
    { 203, { "textBlackNoteFracSingle16th", 0xF7D6, "", SmuflGlyphSource::Finale } },
    { 204, { "metNote64thUp", 0xECAD, "", SmuflGlyphSource::Smufl } },
    { 206, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl } },
    { 207, { "accidentalDoubleSharp", 0xE263, "", SmuflGlyphSource::Smufl } },
    { 210, { "rest8th", 0xE4E6, "", SmuflGlyphSource::Smufl } },
    { 211, { "metNoteHalfUp", 0xECA3, "", SmuflGlyphSource::Smufl } },
    { 212, { "restQuarter", 0xE4E5, "", SmuflGlyphSource::Smufl } },
    { 217, { "metNote16thUp", 0xECA9, "", SmuflGlyphSource::Smufl } },
    { 218, { "metricModulationArrowLeft", 0xEC63, "", SmuflGlyphSource::Smufl } },
    { 219, { "metNote32ndUp", 0xECAB, "", SmuflGlyphSource::Smufl } },
    { 248, { "dynamicPP", 0xE52B, "", SmuflGlyphSource::Smufl } },
    { 305, { "metNoteDoubleWholeSquare", 0xECA1, "", SmuflGlyphSource::Smufl } },
    { 338, { "metNoteQuarterUp", 0xECA5, "", SmuflGlyphSource::Smufl } },
    { 710, { "metNoteDoubleWhole", 0xECA0, "", SmuflGlyphSource::Smufl } },
    { 732, { "accidentalSharp", 0xE262, "", SmuflGlyphSource::Smufl } },
    { 8730, { "accidentalDoubleFlat", 0xE264, "", SmuflGlyphSource::Smufl } },
    { 61667, { "metNoteWhole", 0xECA2, "", SmuflGlyphSource::Smufl } },
    { 61668, { "metNote8thUp", 0xECA7, "", SmuflGlyphSource::Smufl } },
};

} // namespace smufl_mapping::detail::legacy
