// This file is generated from Patmm.json
//
// SPDX-FileCopyrightText: Generated by smufl_mapping (2026)
// SPDX-License-Identifier: MIT
//
// Source project: https://github.com/rpatters1/smufl-mapping
//
// This header was generated from SMuFL font metadata provided by SMuFL and Finale
// and is part of the internal implementation of the smufl_mapping project.
//
// To regenerate this file, run tools/generate_glyphnames_map.py
#pragma once

#include "smufl_mapping.h"

namespace smufl_mapping::detail::legacy {

constexpr std::pair<char32_t, LegacyGlyphInfo> patmmLegacyGlyphs[] = {
    { 162, { "accidentalNatural", 0xE261, "", SmuflGlyphSource::Smufl, false } },
    { 163, { "accidentalDoubleFlat", 0xE264, "", SmuflGlyphSource::Smufl, false } },
    { 165, { "metNote8thUp", 0xECA7, "", SmuflGlyphSource::Smufl, false } },
    { 167, { "accidentalDoubleSharp", 0xE263, "", SmuflGlyphSource::Smufl, false } },
    { 176, { "accidentalSharp", 0xE262, "", SmuflGlyphSource::Smufl, false } },
    { 182, { "accidentalThreeQuarterTonesSharpArrowUp", 0xE274, "", SmuflGlyphSource::Smufl, false } },
    { 223, { "accidentalQuarterToneSharpNaturalArrowUp", 0xE272, "", SmuflGlyphSource::Smufl, false } },
    { 8224, { "accidentalFlat", 0xE260, "", SmuflGlyphSource::Smufl, false } },
    { 8226, { "accidentalQuarterToneFlatArrowUp", 0xE270, "", SmuflGlyphSource::Smufl, false } },
    { 8706, { "metNote16thUp", 0xECA9, "", SmuflGlyphSource::Smufl, false } },
    { 8719, { "metNoteWhole", 0xECA2, "", SmuflGlyphSource::Smufl, false } },
    { 8734, { "metNoteQuarterUp", 0xECA5, "", SmuflGlyphSource::Smufl, false } },
    { 8804, { "metNoteHalfUp", 0xECA3, "", SmuflGlyphSource::Smufl, false } },
};

} // namespace smufl_mapping::detail::legacy
